- mailmerge/api.py
Fixed code to remove the custom attachment header (that shouldn't be included in the final email).
> [Bugfix] Remove custom attachment header in sent emails

- mailmerge/api.py
- setup.py
As python2 moves closer and closer to EOL backports and other packages
from python2 are being dropped.  This makes those conditionally used
so that python3 primary distributions work
> Support distros dropping python2 support

- mailmerge/api.py
- tests/test_mailmerge.py
- tests/testdata/bad_template.txt
Show an error to the user if Jinja template uses a variable that's not provided in the context.
> Strict jinja

- tox.ini
Linters fail on Python 2 because pydocstyle dropped support from Python < 3.4.  Run linters only on Python 3.
> Run linters on Python 3 only

- mailmerge/template_message.py
- tests/test_template_message.py
- tests/testdata/markdown_template_utf8.txt
Currently, when converting a non-multipart message to multipart, the code gets the raw payload and attaches that to a new multipart message. (We lose the encoding metadata.) In the example described in #59, the non-multipart message was encoded using UTF-8+Base64, but the multipart message contained the Base64 string without specifying that encoding scheme (which defaulted to ascii).
To fix this, the code should do the following when creating a multipart message (or converting to Markdown):
1. Retain the original encoding information
2. Base64-decode the plaintext before attaching it to the new multipart email (otherwise, the original message is base64-encoded multiple times)
1. Create a mailmerge template as described in #59.
2. Run `mailmerge`
3. Output is correctly encoded using …
> Decode message converting to multipart

- mailmerge/__main__.py
- tests/test_mailmerge.py
The mailmerge CLI help message is good, but the README better describe the workflow for using the tool. (The help message also doesn't document features such as attachments and markdown.)
This PR updates the help message with a link to this repository's README. Suggestions for language are welcome 😄
> Add README URL to help message

- mailmerge/template_message.py
- setup.py
- tests/test_template_message.py
- tests/testdata/emoji_database_template.txt
- tests/testdata/emoji_markdown_template.txt
- tests/testdata/emoji_template.txt
Closes #61.  Also closes #46 because this PR removes the `chardet` library dependency.
See the new unit tests `test_emoji_*` in `tests/test_template_message.py`.
> Bug fix: emoji

- mailmerge/__main__.py
- tests/test_mailmerge.py
Fix error introduced by #62 .  Running `mailmerge` with no options results in exception.
> Fix error with no options

- mailmerge/__main__.py
- tests/test_main.py
It's irrelevant to hint the user to `--resume 1`. The first message is the default, and this hint is confusing.
> Avoid irrelevant hints

- mailmerge/template_message.py
- tests/test_template_message.py
As described in #94, messages that are "made multipart" by `mailmerge` (only with attachments though) are sent with duplicate `Content-Type` and `MIME-Version` headers. 
This PR removes the duplicate headers, and updates the tests to be able to expose the issue in case of a regression.
Thanks @asadbd07 for sharing the basis for this fix!
Closes #94.
Used the following template:
```
TO: {{email}}
SUBJECT: Testing mailmerge
FROM: My Self <myself@mydomain.com>
ATTACHMENT: tests/testdata/attachment_1.txt
Test
```
Ran `mailmerge --output-format raw --limit 1`.
Before this PR (notice the duplicated headers):
```
>>> message 1
Content-Type: multipart/alternative;
boundary="===============7959594431702800747=="
MIME-Version: 1.0
SUBJECT: Testing mailmerge
TO: myself@mydomain.com
Content-Type: …
```
> Remove duplicate headers in multipart emails

- mailmerge/__main__.py
Default encoding on Windows systems is [cp1252](https://en.wikipedia.org/wiki/Windows-1252)
`encoding="utf-8"` fixes the issue with `UnicodeDecodeError` when `mailmerge_database.csv` contains Unicode characters in localized languages.
Thanks to @seshrs and @awdeorio for guiding me through this 😀
> Add default encoding as UTF-8

- mailmerge/template_message.py
- tests/test_template_message.py
As described in [my comment](https://github.com/awdeorio/mailmerge/issues/100#issuecomment-669970003) in #100, we should preserve the content-subtype of the original message just like we preserve the content's character-encoding. I also added a couple of tests to verify that content-types are correctly processed when using attachments with HTML emails and with MarkDown emails.
Fixes #100.
1) `pytest` fails without the change to `template_message.py`.
2) Use [template](https://github.com/awdeorio/mailmerge/issues/100#issue-673863918) provided by @captn3m0 in #100. Before the fix, the output of `mailmerge --dry-run` shows a content-type of `text/plain`. After the fix, the content-type is `text/html` as expected.
> Retain content-type when adding attachment to non-multipart message

- mailmerge/template_message.py
- tests/test_template_message.py
While testing #115, I noticed that newline characters (`'\n'`) in a markdown template were not rendered on both Gmail and on the native MacOS mail client.
This commit includes the Python Markdown extension [`nl2br`](https://python-markdown.github.io/extensions/nl2br/) to include HTML `<br />` tags whenever single newline characters are present in the Markdown.
I used the following `mailmerge_template.txt`:
```
TO: {{email}}
SUBJECT: Testing mailmerge
FROM: Sesh <sesh.sadasivam@gmail.com>
Content-type: text/markdown
Hi {{ name }},
This is a _mailmerge_ test.
Best,
Sesh
```
In the screenshots below, notice the line-break in `Best, Sesh`.
<table>
<tr>
<th></th>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<th>Gmail</th>
<td><img src="https://user-images.githubusercontent.com/12139762/110223832-a …
> Use New-Line-to-Break markdown extension

- mailmerge/template_message.py
- tests/test_template_message.py
- tests/test_template_message_encodings.py
As discussed in https://stackoverflow.com/a/3984262/5868796, multipart emails should have mime-type `multipart/mixed`. The markdown transformation must embed the text/html message payloads in a `multipart/alternative` payload. Hence, the final payload-structure of an email with attachments transformed by markdown would be:
- `multipart/mixed`
- `multipart/alternative`
- `text/plain`
- `text/html`
- `attachment 1`
- `attachment 2`
- ...
This PR fixes the email structure of multipart messages with attachments and/or contain transformed Markdown. This commit also updates the unit tests to check for the above structure.
Closes #113.
I sent an email with Markdown and an attachment, and viewed the email on Gmail and on the native MacOS Mail client. The email showed correctly in both cases: …
> Fix multipart email structure

- .editorconfig
- MANIFEST.in
Since PyLint is strict when it comes to style, It heps for developers to have a `.editorconfig` file and an editor that supports it.
> User and EditorConfig to help with style

- mailmerge/template_message.py
- mailmerge/utils.py
- setup.py
- tests/test_ratelimit.py
- tests/test_sendmail_client.py
Use idiomatic `pytest-mock` instead of `mock` in unit tests.
> Refactor test mocking

- mailmerge/__main__.py
- tests/test_main.py
- tests/testdata/mailmerge_database_with_BOM.csv
Correctly handle CSV files containing a Byte Order Mark (BOM).
Closes #93
> Bug Fix: CSV with BOM

- .github/workflows/main.yml
- tests/test_helpers.py
- tests/test_template_message.py
- tox.ini
pydocstyle was failing to find files, used a shell glob to fix.
This PR also fixes a codecov GitHub Actions problem by bumping the version.
> Fix tox config for pydocstyle

- mailmerge/template_message.py
- tests/test_template_message.py
Change the content type from `multipart/mixed` to `multipart/related` so
that thunderbird will correctly recognize inline images.
Closes #142
> Change mimetype to support inline images in thunderbird

- .github/workflows/main.yml
- mailmerge/template_message.py
Remove Python 3.6 and 3.7, which are at [end of life](https://devguide.python.org/versions/) and causing CI failures.  Add Python 3.10 and Python 3.11 in CI tests.  Fix a lint error on most recent pylint.
> Drop Python 3.6 from CI

- README.md
- mailmerge/__main__.py
- mailmerge/sendmail_client.py
- tests/test_sendmail_client.py
Adds OAuth based authentication.
Fixes https://github.com/awdeorio/mailmerge/issues/150
> Add XOAUTH2 authentication

- mailmerge/__main__.py
Pylint added a new `use-yield-from` in [version 3.1]. This results in a single linting error when running `tox`. This change updates a `yield` within a loop to a `yield from` per the linter's recommendation.
[version 3.1]: https://pylint.readthedocs.io/en/stable/whatsnew/3/3.1/
> Update a yield statement loop to a yield from statement

- .github/workflows/main.yml
- tox.ini
This commit includes two changes:
1. Removes py36 and py37 from the `tox` `envlist` to match the CI changes made in #148
2. Adds Python 3.12 to both `tox.ini` and the GitHub Actions configuration to ensure that the current major version of Python is included in the test suite
> Update tox envlist

- .github/workflows/main.yml
- mailmerge/__main__.py
Fix errors due to changes in pylint https://github.com/pylint-dev/pylint/issues/9099
> Fix pylint error
